version: '3.9'

services:
  db:
    image: "postgres:14.0-alpine"
    restart: always
    volumes:
      - volume:/var/lib/postgresql/data/
      - ./db:/docker-entrypoint-initdb.d/
    networks:
      - network 
    ports:
      - "5432:5432"
    environment:
        POSTGRES_HOST: localhost
        POSTGRES_DB: db
        POSTGRES_USER: root
        POSTGRES_PASSWORD: postgres

volumes:
  volume:

networks:
  network: